name: Backend CI

on:
  push:
    branches-ignore:
      - 'refs/pull/**'
    paths:
      - 'entrypoint-backend/**'
  pull_request:
    paths:
      - 'entrypoint-backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Check code formatting
        working-directory: ./entrypoint-backend
        run: ./gradlew spotlessCheck --no-daemon

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: ./.github/actions/setup-java

      - name: Run all tests
        working-directory: ./entrypoint-backend
        run: ./gradlew test --no-daemon
